### ISSUE TITLE
Align text with ruler

### ISSUE THREAD

**Issue by JonathonRP** [techniq/layerchart#149]
Is there a way to align text or label ruler for average/ custom value?

**Comment by techniq** [comment]
btw, these kind of questions might be easier on Discord, but here works too.  Discord can be nice to chat back and forth.

**Comment by techniq** [comment]
@JonathonRP Something like this..

![image](https://github.com/techniq/layerchart/assets/177476/b8348294-21d4-45cb-9489-d1a70e586506)

**Comment by JonathonRP** [comment]
> @JonathonRP Something like this..
> 
> ![image](https://github.com/techniq/layerchart/assets/177476/b8348294-21d4-45cb-9489-d1a70e586506)

Yes, close enough, I wanted value and label on both sides but this is good enough

**Comment by techniq** [comment]
Discussed further on [Discord](https://discord.com/channels/920755200552226868/1233076184238133290), and [updated](https://github.com/techniq/layerchart/commit/eb1523601f50ec455a1156947b9b46b9b9a78e74) vertical/horizontal examples.  Instead of `<Point>`, just leveraged `let:yScale` and `<Text y={yScale(avg)} />`
