### ISSUE TITLE
Hover Display Not Aligning with Mouse Position

### ISSUE THREAD

**Issue by AskDavis** [techniq/layerchart#239]
Hello! Hopefully this will be an easy fix, but I can't seem to get the mouse to align with the bisect-x. Wondering if anyone else is having this issue?

Layerchart Version - 0.44.0
Svelte Version - 4.2.7
Tailwindcss Version - 3.4.9

Hover cursor over chart in this reproducible sample code shows your cursor to the right of the datapoints not allowing to overlap by about 16px. This makes it so I can't hover over the last datapoint. 

 - Here's the Svelte REPL: https://svelte.dev/repl/bb4ac8dd5e0f48d9a37249392dcf01b3?version=4.2.19

What am I missing?
Thanks!
AskDavis

**Comment by techniq** [comment]
Hey @AskDavis 👋, thanks for checking out LayerChart.

I see you are using `scaleBand()` with `bisect-x` and time series (date) data.   Instead of `scaleBand()`, I would recommend `scaleTime()` or `scaleUtc()` and convert the date strings `'2023-01-05'` to `Date` instances, either by updating the data...

```js
const investmentData = [
    { date: new Date('2023-01-05'), value: 5000 },
    { date: new Date('2023-01-06'), value: Math.floor(Math.random() * (8500 - 5000)) + 5000 },
    ...
  ];
```

processing the data...
```js
const investmentData = [
    { date: '2023-01-05', value: 5000 },
    { date: '2023-01-06', value: Math.floor(Math.random() * (8500 - 5000)) + 5000 },
    ...
  ].map(d => ({ ...d, date: new Date(d.date) }));
```

or change the `x` accessor from

```svelte
<Chart x="date" ...>
```
to
```svelte
<Chart x={d => d.date} ...>
```

Note: in the upcoming Simplified Charts PR, [LineChart](https://techniq-simplified-charts.layerchart.pages.dev/docs/components/LineChart) will smartly [switch](https://github.com/techniq/layerchart/blob/simplified-charts/packages/layerchart/src/lib/components/charts/LineChart.svelte#L63-L64) between `scaleLinear()` and `scaleTime()` based on the data type of `x`.

Hope that gets you going.

**Comment by AskDavis** [comment]
that fixed it! amazing! thank you so much! I really love LayerChart!! amazing work and can't thank you enough :)

**Comment by AskDavis** [comment]
that fixed it! amazing! thank you so much! I really love LayerChart!! amazing work and can't thank you enough :)

**Comment by techniq** [comment]
You're very welcome, and glad you're enjoying it 😃.  The new simplified charts will help provider a better onboarding experience (and just generally simplifier)
