### ISSUE TITLE
Triple Y Axis

### ISSUE THREAD

**Issue by cycle4passion** [techniq/layerchart#247]
I am using the stacked Charts technique to do and overlay of 3 charts with 3 Y axises. One Axis is shown on left, the other 2 are on the right. As expected, the 2 on the right have overlapping scales and labels for obvious reasons. I am looking for a way to shift one Axis over. 

<img width="1001" alt="Screenshot 2024-09-24 at 4 37 27 PM" src="https://github.com/user-attachments/assets/2bfad4b8-b2cb-40c7-9d1a-583d279e2643">

Steps Taken without success.
1. Looked at Axis props, I don't think there is anything here. Do I need support for dX and dY in Axis?
2.  Tried wrapping div around one Y Axis, and adding padding or margin without success.

**Comment by techniq** [comment]
Hey @cycle4passion, that's an interesting problem.  One quick thought/hack is using `tickLabelProps` and `tickLength` to invert the [alignment](https://github.com/techniq/layerchart/blob/main/packages/layerchart/src/lib/components/Axis.svelte#L152-L158) of the axis labels so they show to the left side of the second right axis line.

```svelte
<Axis placement="right" rule />
<Axis placement="right" tickLabelProps={{ dx: -4, textAnchor: "end" }}  tickLength={-4} />
```

![image](https://github.com/user-attachments/assets/3bd25b23-7e5b-4e1d-9051-48b9856cb1db)

I could envision adding a `tickLabelPlacement` prop with `start` / `end` or `inside` / `outside` to simplify this inverting, but would need to give it some more thought.

**Comment by cycle4passion** [comment]
BTW, Thank you for a great library! Your suggestion is quite helpful. If you were to implement tickLabelPlacement, I worry that that iy might get a little cluttered if label is too long. This is a prior rendition in a different library showing a different approach.

<img width="1007" alt="Screenshot 2024-09-25 at 4 55 06 PM" src="https://github.com/user-attachments/assets/53e41ac2-ff2e-4a67-8af5-41e901a293b5">

**Comment by techniq** [comment]
Thanks for the kind words 😀, and that example is very helpful for the desired result. I have some ideas but AFK.  I'll try to test out the idea later tonight if I get some time.

**Comment by techniq** [comment]
Something like this?
![image](https://github.com/user-attachments/assets/eb83d4e9-eda7-4a6f-a692-39a577afadb8)

To make this work, I did the following:
- [Added](https://github.com/techniq/layerchart/pull/248/commits/fdd2ff240f6b179d8985a6744674c76645d64bd8) support to pass `<Axis class="...">` (as well as `<Axis classes={{ root: '...', label: '...' }}>)`.  This PR should get deployed in a day or two once I wrap up a few more items
- Used `<Chart padding={{ right: 80, .... }}>` to give enough room for both right axises
- Used `<Axis class="translate-x-[50px]" labelProps={{ dx: -50 }}>` on the right-most axis to shift the container (and thus line) to the right 50px and and then brought the label back 50px (as labels are always aligned to the edge of the chart, regardless of the padding, but shifting it's the container required offsetting).
- Used `<Axis labelProps={{ dx: -50 }}>` on the inside right axis to shift it's label closer to the line), as otherwise it would be on the Chart's right most edge, and thus on top of the other label.

Here's the full example:

```svelte
<div class="h-[300px] p-4 border rounded">
  <Chart
    data={dateSeriesData}
    x="date"
    xScale={scaleTime()}
    y="value"
    yDomain={[0, null]}
    yNice
    padding={{ left: 16, right: 80, bottom: 24 }}
  >
    <Svg>
      <Axis placement="left" grid rule />
      <Axis
        placement="right"
        rule
        label="Velocity (ng/ml/year)"
        labelProps={{ dx: -50 }}
      />
      <Axis
        placement="right"
        rule
        label="Doubling Time (years)"
        class="translate-x-[50px]"
        labelProps={{ dx: -50 }}
      />
      <Axis
        placement="bottom"
        format={(d) => format(d, PeriodType.Day, { variant: "short" })}
        rule
      />
      <Area
        line={{ class: "stroke-2 stroke-primary" }}
        class="fill-primary/30"
      />
    </Svg>
  </Chart>
</div>
```

**Comment by cycle4passion** [comment]
Wow. Remarkably quick turn around for exactly what I needed. Thank you. Patiently awaiting next update. Hopefully it wasn't too niche.

**Comment by techniq** [comment]
Hot off the presses - [0.52.0](https://github.com/techniq/layerchart/releases/tag/layerchart%400.52.0)
