### ISSUE TITLE
Sorting issues in Tooltip examples 

### ISSUE THREAD

**Issue by mattlangeman** [techniq/layerchart#56]
### Issue
Incorrect sorting of data on examples similar to [Single Date / Time Example](https://www.layerchart.com/docs/components/Tooltip#single-date-/-time-%3Csmall%3Ex:-scaletime,-y:-scaleband%3C/small%3E)

`item 10` getting put between `item 1` and `item 2`

### Details
Almost surely caused by the same Layer Cake sorting change mentioned in issue #54 

### Solution?
Quickest fix is changing the examples to include:

`yDomain={[...new Set(timeSeries.map((d) => d.name))]}`

**Comment by techniq** [comment]
Sadly, I think that's the only way to maintain the order of the source data.  I'm not overly sold on this change TBH, but I think it's the best we can do right now.

https://svelte.dev/repl/0b588c652ee64658b96b81bd7f7899cd?version=4.2.1

**Comment by techniq** [comment]
Actually... this might be possible to use `localeCompare` or `Intl.Collator`, although not sure how difficult this would be to support non-en 

![image](https://github.com/techniq/layerchart/assets/177476/c5a52a94-2ed4-459e-ad4c-c4a3ffae546e)

I updated the [REPL](https://svelte.dev/repl/0b588c652ee64658b96b81bd7f7899cd?version=4.2.1)

This came from a Stack Overflow - https://stackoverflow.com/questions/4340227/sort-mixed-alpha-numeric-array

**Comment by techniq** [comment]
@mhkeller Thoughts to do this within Layer Cake? ☝️

**Comment by mhkeller** [comment]
If I understand this right, this is the order that d3.ascending gives right? I’m open to being convinced for a reason to add an option to not sort and just go by the order in the data but my thinking is that if you care about the order being in a specific way then passing in a domain is the way to ensure that order — otherwise the source data could change and the chart has no guarantee of the right order

**Comment by techniq** [comment]
@mhkeller It's the order of `d3.ascending`, but also how most general sorting works since `item 10` > `item 9` is `false`, but `localeCompare()` or `Intl.Collator()` handles this (and more what the user expects).

![image](https://github.com/techniq/layerchart/assets/177476/91c90e39-9ef9-4af8-91ee-8a5b3ac03e5b)

See [this](https://stackoverflow.com/questions/4340227/sort-mixed-alpha-numeric-array) Stack Overflow discussion for another example and comparison between the 3 (basic `<` / `>`, `localeCompare()` and `Intl.Collator()`).

I think switching to either `localeCompare()` and `Intl.Collator()` should just be a simple drop in replacement.  The only big question is how to handle the the language, particular within SSR.

I think the choices are:

- Just hard code it to `en`.  While not optimal, it's still better than it is now
- Use `navigator.language` client side, and `en` server side, although I think the inconsistency between client/server would cause other issues.  If we had access to the SSR request, we could use the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header, but this is challenging for a library

I'm personally leaning towards just a hard coded `en`

**Comment by techniq** [comment]
@mhkeller Well, I gave `Intl.Collator()` a quick try, but there are 5 failing tests, but also the one I added that should be fixed by this... so I'm perplexed.

_ | _
--- | ---
![image](https://github.com/techniq/layerchart/assets/177476/76444db8-1f35-4798-bf85-414f55af033e) | ![image](https://github.com/techniq/layerchart/assets/177476/1486cdac-04f2-46b6-af55-11968f188210)

If I test this in isolation, it works as expected 🤷‍♂️...

![image](https://github.com/techniq/layerchart/assets/177476/ad34ef75-02cc-4989-b81b-d80757247841)

**Comment by techniq** [comment]
well, I thought it was maybe node-specific (almost like it was ignoring the `numeric: true` option), but my quick experiment seems to disprove that.

![image](https://github.com/techniq/layerchart/assets/177476/decd47e5-e9e2-4c86-9810-bdce90cf08a8)

@mhkeller no rush, but could you try to do the same by swapping `d3.ascending` for either

```js
const sorter = Intl.Collator('en', { numeric: true, sensitivity: 'accent' }).compare;
```
or 
```js
const sorter = (a, b) => a.toString().localeCompare(b.toString(), 'en', { numeric: true });
```
and see if the tests pass for you.  

This was the extra alphanumeric test I added to `calcUniques.test.ts`.

```js
// alphanumeric
{
	args: [
		[
			{ x: 'A1' },
			{ x: 'A10' },
			{ x: 'A11' },
			{ x: 'A12' },
			{ x: 'A2' },
			{ x: 'A3' },
			{ x: 'A4' },
			{ x: 'B10' },
			{ x: 'B2' },
			{ x: 'F1' },
			{ x: 'F12' },
			{ x: 'F3' }
		],
		{ x: (d) => d.x }
	],
	expected: {
		x: ['A1', 'A2', 'A3', 'A4', 'A10', 'A11', 'A12', 'B2', 'B10', 'F1', 'F3', 'F12']
	}
}
```

**Comment by mhkeller** [comment]
The `xDomain` prop takes a function. Can you apply your custom sort onto that? I'm pretty hesitant to apply such a specific sort opinion as the default.

**Comment by techniq** [comment]
@mhkeller we can use the xDomain prop. Not worth the complexity for LauerCake at this point. Thanks. 

@mattlangeman care to PR that change?
