### ISSUE TITLE
installation error  missing peer sveld

### ISSUE THREAD

**Issue by xmlking** [techniq/layerchart#91]
installation error  `missing peer sveld`
is `sveld` a required dependency ?
  
<img width="564" alt="image" src="https://github.com/techniq/layerchart/assets/627951/a092f57f-8dbc-4580-9628-875351294adb">

**Comment by techniq** [comment]
It is/was misclassified in `0.56.x`/`0.57.x` ([package.json](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/package.json#L75)) (along with others) but we did a lot of cleanup in the upcoming [next](https://github.com/techniq/svelte-ux/blob/next/packages/svelte-ux/package.json#L74) release.  As of right now we moved `sveld` to a `dependency` only because of it's use in the [vite plugin](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/plugins/vite.js) that Svelte UX exposes and LayerChart consumes.  At some point we probably need to leverage some additional packages in the Svelte UX mono repo to help separate these kind of dependencies.

Once `next` becomes `latest` (planning by end of month, but hopefully sooner), this `peerDependency` will go away.  In the interim, it does exist.

**Comment by xmlking** [comment]
Thanks @techniq 
Looking forward to try next

**Comment by techniq** [comment]
Welcome :).  It's in the home stretch, mostly just testing/dogfooding and documentation.  I've also got a lot going on personally ATM so my time has been a spotty.

**Comment by techniq** [comment]
`next` is now released, and this should no longer be an issue.
