### ISSUE TITLE
Accent extended color in used already.

### ISSUE THREAD

**Issue by pitzzahh** [techniq/layerchart#94]
I am using shadcn-svelte and they have populated the `accent` extended color. I do not want to touch that. Instead, I want to make an extended color of green. My app works and the charts work because I changed the classes to use my green extended color. However, a little warning appears when I run `pnpm dev`

```js
import { fontFamily } from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
const config = {
	darkMode: ["class"],
	content: [
		'./src/**/*.{html,svelte,js,ts}',
		'./node_modules/svelte-ux/**/*.{svelte,js}',
		'./node_modules/layerchart/**/*.{svelte,js}',
	],
	safelist: ["dark"],
	theme: {
		container: {
			center: true,
			padding: "1rem",
			screens: {
				"2xl": "1400px"
			}
		},
		extend: {
			colors: {
				border: "hsl(var(--border) / <alpha-value>)",
				input: "hsl(var(--input) / <alpha-value>)",
				ring: "hsl(var(--ring) / <alpha-value>)",
				background: "hsl(var(--background) / <alpha-value>)",
				foreground: "hsl(var(--foreground) / <alpha-value>)",
				primary: {
					DEFAULT: "hsl(var(--primary) / <alpha-value>)",
					foreground: "hsl(var(--primary-foreground) / <alpha-value>)"
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
					foreground: "hsl(var(--secondary-foreground) / <alpha-value>)"
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
					foreground: "hsl(var(--destructive-foreground) / <alpha-value>)"
				},
				muted: {
					DEFAULT: "hsl(var(--muted) / <alpha-value>)",
					foreground: "hsl(var(--muted-foreground) / <alpha-value>)"
				},
				accent: {
					DEFAULT: "hsl(var(--accent) / <alpha-value>)",
					foreground: "hsl(var(--accent-foreground) / <alpha-value>)"
				},
				popover: {
					DEFAULT: "hsl(var(--popover) / <alpha-value>)",
					foreground: "hsl(var(--popover-foreground) / <alpha-value>)"
				},
				card: {
					DEFAULT: "hsl(var(--card) / <alpha-value>)",
					foreground: "hsl(var(--card-foreground) / <alpha-value>)"
				},
				green: {
					100: '#4EF18A',
					200: '#3BEA7A',
					300: '#2EE56B',
					400: '#25D95F',
					500: '#1FC953',
					600: '#1ABD49',
					700: '#16B23F',
					800: '#11A635',
					900: '#0D9B2B'
				}
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)"
			},
			fontFamily: {
				sans: [...fontFamily.sans]
			}
		}
	},
	plugins: [require('svelte-ux/plugins/tailwind.cjs')],
};

export default config;
```

`warn - The utility `[--color:theme(colors.accent.500)]` contains an invalid theme value and was not generated.`

**Comment by techniq** [comment]
Hi @pitzzahh 👋.  A few thoughts:

At the moment LayerChart (and Svelte UX) use a single statically defined `accent` color to add some theming.  Both projects have huge releases coming which move to a CSS variable theming, similar to shadcn, skeleton, and others.  They are both publishes as `@next` and all that remains is some dogfooding on some of my projects (and a few others have been as well) as well as writing docs.

You can see both of these versions in action here:

- https://next.svelte-ux.pages.dev/
- https://design-tokens.layerchart.pages.dev/

With that said, I'm also looking to understand and improve the interop stories between LayerChart and ShadCN / Skeleton as I have only experimented with each of these and use Svelte UX.

LayerChart has a very small dependency on Svelte UX, but 99% of it is under the hood, utilizing things like the `cls()` util.

With that said, the theme colors for Svelte UX (and which LayerChart can leverage) has been expanded to include..

- primary-[50-900] and default
- secondary-[50-900] and default
- accent-[50-900] and default
- neutral-[50-900] and default
- info-[50-900] and default
- success-[50-900] and default
- warning-[50-900] and default
- danger-[50-900] and default
- surface-[100,200,300]
- surface-content

You can see these theme colors on the new theme generator [here](https://next.svelte-ux.pages.dev/theme).


With all that context, I think the interop between LayerChart and ShadCN will be much better.  While there is an `accent` color, it is
- A CSS variable
- You can change the color space to hsl(), rgb(), or oklch().  hsl() is the default, and is also what ShadCN uses

Reading your message closer... the warning `[--color:theme(colors.accent.500)]`.  This is likely something you are doing explicitly, probably from copying one of the LayerChart examples.  Since ShadCN only registers the 1 value (`accent`) and not all shades (`accent-100`, `accent-500`, etc`) as well as the DEFAULT (`accent`), this is why the error is coming up.  You should be able to change this to `[--color:theme(colors.accent)]` or reference the CSS variable directly using `hsl(var(--color-accent))`.  I've done this a lot in the new LayerChart docs, such as the [Calendar](https://design-tokens.layerchart.pages.dev/docs/components/Calendar) example.

Hopefully that helps explain where things are going, and provide a solution for you now.

**Comment by pitzzahh** [comment]
> Hi @pitzzahh 👋. A few thoughts:
> 
> At the moment LayerChart (and Svelte UX) use a single statically defined `accent` color to add some theming. Both projects have huge releases coming which move to a CSS variable theming, similar to shadcn, skeleton, and others. They are both publishes as `@next` and all that remains is some dogfooding on some of my projects (and a few others have been as well) as well as writing docs.
> 
> You can see both of these versions in action here:
> 
> * https://next.svelte-ux.pages.dev/
> * https://design-tokens.layerchart.pages.dev/
> 
> With that said, I'm also looking to understand and improve the interop stories between LayerChart and ShadCN / Skeleton as I have only experimented with each of these and use Svelte UX.
> 
> LayerChart has a very small dependency on Svelte UX, but 99% of it is under the hood, utilizing things like the `cls()` util.
> 
> With that said, the theme colors for Svelte UX (and which LayerChart can leverage) has been expanded to include..
> 
> * primary-[50-900] and default
> * secondary-[50-900] and default
> * accent-[50-900] and default
> * neutral-[50-900] and default
> * info-[50-900] and default
> * success-[50-900] and default
> * warning-[50-900] and default
> * danger-[50-900] and default
> * surface-[100,200,300]
> * surface-content
> 
> You can see these theme colors on the new theme generator [here](https://next.svelte-ux.pages.dev/theme).
> 
> With all that context, I think the interop between LayerChart and ShadCN will be much better. While there is an `accent` color, it is
> 
> * A CSS variable
> * You can change the color space to hsl(), rgb(), or oklch().  hsl() is the default, and is also what ShadCN uses
> 
> Reading your message closer... the warning `[--color:theme(colors.accent.500)]`. This is likely something you are doing explicitly, probably from copying one of the LayerChart examples. Since ShadCN only registers the 1 value (`accent`) and not all shades (`accent-100`, `accent-500`, etc`) as well as the DEFAULT (`accent`), this is why the error is coming up. You should be able to change this to `[--color:theme(colors.accent)]`or reference the CSS variable directly using`hsl(var(--color-accent))`. I've done this a lot in the new LayerChart docs, such as the [Calendar](https://design-tokens.layerchart.pages.dev/docs/components/Calendar) example.
> 
> Hopefully that helps explain where things are going, and provide a solution for you now.

Hi, Thanks will try that. Yes, I did try out the Clipped area on Tooltip example and just modified the style class there. I'm just starting with this charting stuff and decided to try it. It is cool to use this when building charts with svelte.

**Comment by techniq** [comment]
Sounds good.  If you run into anymore issues, setting up a StackBlitz minimal repo and chatting on Discord can be helpful to troubleshoot.
